### ISSUE TITLE
Logo outdated

### ISSUE THREAD

**Issue by DavidMichaelRoberts** [cemulate/the-mlab#2]
The new logo is genuinely the nLabs, not Instiki's default logo. I think that no one will be fooled by the mLab now that it looks nothing like the nLab.

Alternatively, you could have a 'mLab classic' toggle switch to provide for people's nostalgia... :-P

**Comment by cemulate** [comment]
I think a "classic switch" is a great idea. I did see the nLab got a bit of a makeover quite a while ago, but haven't yet carved out some time to recreate the makeover myself. Pull requests are 100% welcome but it's on my personal todo list as well!

**Comment by cemulate** [comment]
The makeover has been done!
